export const TODAY='2026-09-13';
export function seed(){
 const symptoms=[2,0,3,1,4,null,2,1,3,2,1,4,2];
 const sleeps=[7.4,8,6.1,7.8,5.6,null,7.1,8.2,6.3,7.2,7.9,5.8,7.4];
 return {version:1, observations:symptoms.flatMap((v,i)=>v===null?[]:[{id:'day-'+i,date:`2026-09-${String(i+1).padStart(2,'0')}`,symptom:'Headache',severity:v,sleep:sleeps[i],note:i===11?'Busy afternoon; rested at home.':'Sample daily check-in',source:'Sample journal'}]),questions:[{id:'q1',text:'What should I keep track of between appointments?'},{id:'q2',text:'Could we discuss the pattern in my headache journal?'},{id:'q3',text:'Which changes should prompt me to contact the clinic?'}],records:[{id:'r1',title:'Follow-up consultation',type:'Visit note',date:'2026-08-28',provider:'Sample primary care clinic',body:'DEMONSTRATION RECORD — FICTIONAL PATIENT\nPatient: Maya Tan\nDate: 28 August 2026\nHistory: Recurrent headaches reported by patient.\nFollow-up: Bring symptom journal to next appointment.\nDocumented medication: No medication details supplied in this sample.\nThis sample contains no treatment instructions.'},{id:'r2',title:'Health screening results',type:'Lab report',date:'2026-08-12',provider:'Sample screening centre',body:'DEMONSTRATION RECORD — FICTIONAL PATIENT\nPatient: Maya Tan\nDate: 12 August 2026\nHaemoglobin: 13.1 g/dL\nLaboratory reference range: 12.0–15.5 g/dL\nDo not use synthetic values for health decisions.'}],messages:[],reminders:[{id:'rem1',text:'Evening check-in',time:'20:30',active:true},{id:'rem2',text:'Prepare appointment questions',time:'18:00',active:true}],family:{active:true,records:false,journal:true,visits:true},medications:[{name:'Medication list',detail:'Add only medication information provided by your clinician.',reported:false}],pending:null};
}
export function addObservation(state, entry){return {...state,observations:[...state.observations,{id:entry.id||'obs-'+Date.now(),source:'Conversation',...entry}]};}
export function editObservation(state,id,patch){return {...state,observations:state.observations.map(o=>o.id===id?{...o,...patch}:o)};}
export function removeObservation(state,id){return {...state,observations:state.observations.filter(o=>o.id!==id)};}
export function stats(state){let rows=state.observations.filter(o=>o.symptom.toLowerCase()==='headache'&&Number.isFinite(o.severity));return {entries:state.observations.length,days:new Set(rows.map(o=>o.date)).size,average:rows.length?rows.reduce((s,o)=>s+o.severity,0)/rows.length:null,headacheDays:new Set(rows.filter(o=>o.severity>0).map(o=>o.date)).size};}
export function comparison(state){let pairs=state.observations.filter(o=>o.symptom.toLowerCase()==='headache'&&Number.isFinite(o.sleep)&&Number.isFinite(o.severity));let groups=[pairs.filter(o=>o.sleep<7),pairs.filter(o=>o.sleep>=7)];return groups.map((r,i)=>({label:i?'7 hours or more':'Under 7 hours',count:r.length,average:r.length?r.reduce((s,o)=>s+o.severity,0)/r.length:null}));}
export function brief(state){let s=stats(state);return `MAYA TAN — DEMONSTRATION APPOINTMENT BRIEF\nSynthetic data. Patient-prepared; not a clinical assessment.\nAppointment: 18 September 2026, 10:30am\nReporting period: 1–13 September 2026\n\nWHAT I WOULD LIKE TO DISCUSS\n${state.questions.map((q,i)=>`${i+1}. ${q.text}`).join('\n')}\n\nMY JOURNAL\n${s.entries} observations across ${s.days} days. Average recorded severity: ${s.average===null?'Not available':s.average.toFixed(1)} / 5. Unlogged days are unknown.\n${state.observations.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6).map(o=>`${o.date}: ${o.symptom}, ${o.severity??'unknown'}/5. ${o.note} [${o.source}]`).join('\n')}\n\nRECORDS AVAILABLE\n${state.records.map(r=>`${r.date}: ${r.title} (${r.provider})`).join('\n')}\n\nPatterns are observations to discuss, not proof of a cause.\nGenerated from the current editable demonstration profile.`;}
export function parseDemo(text){let low=text.toLowerCase();if(!/headache|sleep|slept|tired|fatigue/.test(low))return null;let sleep=text.match(/(?:slept|sleep)\s*(?:for\s*)?(\d+(?:\.\d+)?)\s*(?:h|hours)/i);let severity=text.match(/([0-5])\s*(?:\/\s*5|out of 5)/i);return {date:low.includes('yesterday')?'2026-09-12':TODAY,symptom:/headache/.test(low)?'Headache':'Fatigue',severity:severity?+severity[1]:null,sleep:sleep?+sleep[1]:null,note:text,source:'Conversation'};}
export function dailySeries(state){let days=new Map();for(let o of state.observations){let d=days.get(o.date)||{date:o.date,severities:[],sleeps:[]};if(o.symptom.toLowerCase()==='headache'&&Number.isFinite(o.severity))d.severities.push(o.severity);if(Number.isFinite(o.sleep))d.sleeps.push(o.sleep);days.set(o.date,d);}return [...days.values()].sort((a,b)=>a.date.localeCompare(b.date)).map(d=>({date:d.date,severity:d.severities.length?d.severities.reduce((a,b)=>a+b,0)/d.severities.length:null,sleep:d.sleeps.length?d.sleeps.reduce((a,b)=>a+b,0)/d.sleeps.length:null}));}
