import test from 'node:test';import assert from 'node:assert/strict';
import {seed,addObservation,editObservation,removeObservation,stats,comparison,brief,parseDemo} from './model.mjs';
test('capture, correction and deletion propagate into brief and metrics',()=>{let s=seed();let count=stats(s).entries;s=addObservation(s,{id:'test',date:'2026-09-13',symptom:'Headache',severity:5,sleep:4,note:'Unique journal entry'});assert.equal(stats(s).entries,count+1);assert.match(brief(s),/Unique journal entry/);s=editObservation(s,'test',{severity:1,note:'Corrected entry'});assert.match(brief(s),/Corrected entry/);assert.doesNotMatch(brief(s),/Unique journal entry/);s=removeObservation(s,'test');assert.equal(stats(s).entries,count);assert.doesNotMatch(brief(s),/Corrected entry/);});
test('unknown severity and missing days are not zero',()=>{let s=seed();assert.equal(stats(s).days,12);s=addObservation(s,{date:'2026-09-06',symptom:'Fatigue',severity:null,sleep:null,note:'Unknown severity'});assert.equal(stats(s).days,12);assert.equal(comparison(s).reduce((n,g)=>n+g.count,0),12);});
test('empty state yields no pattern or invented average',()=>{let s={...seed(),observations:[]};assert.equal(stats(s).average,null);assert.ok(comparison(s).every(g=>g.average===null));});
test('demo parser preserves uncertainty and extracts only stated values',()=>{assert.equal(parseDemo('I have a headache').severity,null);assert.equal(parseDemo('Yesterday I had a headache, 3/5, and slept 6 hours').sleep,6);assert.equal(parseDemo('Should I change my medication?'),null);});
test('reset creates independent state',()=>{let a=seed();a.questions.pop();assert.equal(seed().questions.length,3);});
import {dailySeries} from './model.mjs';
test('daily chart averages repeated observations and leaves missing date absent',()=>{let s=addObservation(seed(),{date:'2026-09-12',symptom:'Headache',severity:2,sleep:6,note:'Second observation'});assert.equal(dailySeries(s).find(d=>d.date==='2026-09-12').severity,3);assert.equal(dailySeries(s).some(d=>d.date==='2026-09-06'),false);});
