import test from 'node:test';import assert from 'node:assert/strict';
import {createApp} from './server.mjs';import {buildContext,validateChat,fileContent} from './ai-service.mjs';import {seed} from './model.mjs';
const reply={message:'Your sample screening report records haemoglobin.',citations:[{sourceId:'record:r2',quote:'Haemoglobin: 13.1 g/dL'}],observation:null,questions:[]};
const mock=data=>async()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(data)}]}]})});
async function withServer(t,env,fetchImpl){let app=createApp({env,fetchImpl});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{app.close(r);app.closeAllConnections();}));return `http://127.0.0.1:${app.address().port}`;}
const env={OPENAI_API_KEY:'test-key-never-public',DEMO_ACCESS_CODE:'test-code',OPENAI_MODEL:'test-model'};
const request=(base,path,body,code='test-code')=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json','x-demo-code':code},body:JSON.stringify(body)});
test('only public assets are served, no .env, source server, tests or config',async t=>{let base=await withServer(t,env,mock(reply));for(let p of ['/.env','/server.mjs','/ai-service.mjs','/render.yaml','/.git/config'])assert.equal((await fetch(base+p)).status,404);let status=await(await fetch(base+'/api/status')).text();assert.ok(!status.includes(env.OPENAI_API_KEY));assert.ok(!status.includes(env.DEMO_ACCESS_CODE));});
test('missing configuration and wrong access code cannot call AI',async t=>{let calls=0;let base=await withServer(t,{},async()=>{calls++;});assert.equal((await request(base,'/api/chat',{})).status,503);let configured=await withServer(t,env,async()=>{calls++;});assert.equal((await request(configured,'/api/chat',{},'wrong')).status,401);assert.equal(calls,0);});
test('real route sends strict schema and returns checked citations',async t=>{let sent;let base=await withServer(t,env,async(url,options)=>{sent=JSON.parse(options.body);return mock(reply)();});let response=await request(base,'/api/chat',{message:'What does my screening report say?',context:seed(),history:[]});assert.equal(response.status,200);let result=await response.json();assert.equal(result.trace.mode,'live');assert.equal(result.citations[0].title,'Health screening results');assert.equal(sent.store,false);assert.equal(sent.text.format.strict,true);assert.equal(sent.model,'test-model');});
test('unknown sources and fabricated quotes rejected',()=>{let c=buildContext({message:'labs',context:seed()});assert.throws(()=>validateChat({...reply,citations:[{sourceId:'record:fake',quote:'made up'}]},c.sources));assert.throws(()=>validateChat({...reply,citations:[{sourceId:'record:r2',quote:'Haemoglobin: 99'}]},c.sources));});
test('correction changes context hash and current record, old assistant answer excluded',()=>{let s=seed();let one=buildContext({message:'report',context:s,history:[]});s.records[1].body='Corrected record';let two=buildContext({message:'report',context:s,history:[{role:'assistant',text:'Old value 13.1'}]});assert.notEqual(one.contextHash,two.contextHash);assert.equal(two.history.length,0);assert.ok(!JSON.stringify(two.sources).includes('13.1'));});
test('provider failures do not expose credentials or raw upstream errors',async t=>{let base=await withServer(t,env,async()=>({ok:false,status:500,text:async()=>env.OPENAI_API_KEY}));let response=await request(base,'/api/chat',{message:'hello',context:seed()});assert.equal(response.status,502);assert.ok(!(await response.text()).includes(env.OPENAI_API_KEY));});
test('malformed model output rejected without saving anything',async t=>{let base=await withServer(t,env,mock({message:'incomplete'}));assert.equal((await request(base,'/api/chat',{message:'hello',context:seed()})).status,502);});
test('document extraction returns structured fields for review',async t=>{let output={title:'Sample lab',date:null,summary:'A sample value.',fields:[{label:'Haemoglobin',value:'13.1',unit:'g/dL',page:null,quote:'Haemoglobin 13.1 g/dL'}],uncertainties:['Date not visible']};let base=await withServer(t,env,mock(output));let r=await request(base,'/api/extract',{name:'sample.txt',mime:'text/plain',text:'Haemoglobin 13.1 g/dL'});assert.equal(r.status,200);assert.equal((await r.json()).fields[0].unit,'g/dL');});
test('invalid files and oversized input rejected',async t=>{assert.throws(()=>fileContent({name:'fake.pdf',mime:'application/pdf',data:'data:application/pdf;base64,bm90YSBQREY='}));let base=await withServer(t,env,mock(reply));let r=await request(base,'/api/chat',{message:'x'.repeat(260000)});assert.equal(r.status,413);});
